[package]
name = "minira"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
tower-lsp = "0.20.0"
